### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by kongukjae** [jueun11/to-do-list-vanilla-js#1]
1. 리페인트와 리플로우에 대한 개념을 확립할 것
2. javascript로 직접 스타일링 할 것
3. css 의존도를 낮출 것

**Comment by jueun11** [comment]
'생성된 DOM 노드의 레이아웃 변경 시 영향을 받는 모든 노드(부모, 자식)의 수치를 다시 계산하여 레이아웃 트리(렌더 트리)를 재생성하는 작업' 이 리플로우라는데, for문을 쓰던 안쓰던 결국 전부 로딩되는 것은 같다는 것인가요? 
ul의 자식요소로 li하나를 추가해도 레이아웃이 변경된 것으로 간주하여 기존의 다른 li들과 ul도 로딩된다는 것으로 이해했는데 맞게 이해한건지 의문입니다.

++그루핑이나 가상노드나 이것저것 최적화 방법이 많군요! 리플로우를 아예 피할수는 없으니 (리액트의 가상돔이 그리워집니다..) 최대한 최적화 해봐야겠습니다. 감사합니다.
